package com.emmanuelgabe.portfolio.mapper;

import com.emmanuelgabe.portfolio.dto.SiteConfigurationResponse;
import com.emmanuelgabe.portfolio.dto.UpdateSiteConfigurationRequest;
import com.emmanuelgabe.portfolio.entity.SiteConfiguration;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * MapStruct mapper for SiteConfiguration entity and DTOs.
 * Note: profileImageUrl is generated by the service from profileImagePath + basePath.
 */
@Mapper(componentModel = "spring")
public interface SiteConfigurationMapper {

    /**
     * Convert SiteConfiguration entity to SiteConfigurationResponse DTO.
     * profileImageUrl must be set manually by the service.
     *
     * @param siteConfiguration SiteConfiguration entity
     * @return SiteConfigurationResponse DTO
     */
    @Mapping(target = "profileImageUrl", ignore = true)
    SiteConfigurationResponse toResponse(SiteConfiguration siteConfiguration);

    /**
     * Update existing SiteConfiguration entity with values from UpdateSiteConfigurationRequest.
     * Does not update profileImagePath (handled by upload endpoint).
     *
     * @param request UpdateSiteConfigurationRequest DTO
     * @param siteConfiguration Existing SiteConfiguration entity to update
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "profileImagePath", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntityFromRequest(UpdateSiteConfigurationRequest request,
                                  @MappingTarget SiteConfiguration siteConfiguration);
}
