package com.emmanuelgabe.portfolio.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Response DTO for site configuration.
 * Contains all site-wide configuration values.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SiteConfigurationResponse {

    private Long id;

    // Identity
    private String fullName;
    private String email;

    // Hero Section
    private String heroTitle;
    private String heroDescription;

    // SEO
    private String siteTitle;
    private String seoDescription;

    // Profile Image (full URL, generated by service)
    private String profileImageUrl;

    // Social Links
    private String githubUrl;
    private String linkedinUrl;

    // Timestamps
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
