/**
 * Response DTO for site configuration.
 * Contains all site-wide configuration values.
 */
export interface SiteConfigurationResponse {
  id: number;

  // Identity
  fullName: string;
  email: string;

  // Hero Section
  heroTitle: string;
  heroDescription: string;

  // SEO
  siteTitle: string;
  seoDescription: string;

  // Profile Image (full URL generated by backend)
  profileImageUrl: string | undefined;

  // Social Links
  githubUrl: string;
  linkedinUrl: string;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Request DTO for updating site configuration.
 * Profile image is handled separately via upload endpoint.
 */
export interface UpdateSiteConfigurationRequest {
  // Identity
  fullName: string;
  email: string;

  // Hero Section
  heroTitle: string;
  heroDescription: string;

  // SEO
  siteTitle: string;
  seoDescription: string;

  // Social Links
  githubUrl: string;
  linkedinUrl: string;
}
